# Generated by Django 2.2.6 on 2019-10-28 18:47

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('edc', '0002_auto_20191023_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='oplog',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
