# Generated by Django 2.2.6 on 2019-10-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc', '0004_auto_20191028_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cred',
            name='tknfile',
            field=models.FileField(blank=True, null=True, upload_to='protected'),
        ),
        migrations.AlterField(
            model_name='oplog',
            name='exfil',
            field=models.FileField(blank=True, null=True, upload_to='protected'),
        ),
        migrations.AlterField(
            model_name='oplog',
            name='scrsht',
            field=models.FileField(blank=True, null=True, upload_to='protected'),
        ),
    ]
