# Generated by Django 2.2.6 on 2019-10-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc', '0003_oplog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oplog',
            name='cmds',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
