# Generated by Django 2.2.6 on 2019-10-31 18:45

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc', '0005_auto_20191031_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cred',
            name='tknfile',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/var/www/edc_app/protected'), upload_to='protected'),
        ),
        migrations.AlterField(
            model_name='oplog',
            name='exfil',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/var/www/edc_app/protected'), upload_to='protected'),
        ),
        migrations.AlterField(
            model_name='oplog',
            name='scrsht',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/var/www/edc_app/protected'), upload_to='protected'),
        ),
    ]
