# Generated by Django 5.2 on 2025-04-15 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('passwd', models.CharField(blank=True, max_length=60, null=True, verbose_name='Username')),
                ('hashw', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Password')),
                ('token', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Key string')),
                ('tknfile', models.FileField(blank=True, null=True, upload_to='oplog_token/', verbose_name='Cert or keyfile')),
                ('first', models.CharField(blank=True, max_length=32, null=True, verbose_name='First name')),
                ('last', models.CharField(blank=True, max_length=32, null=True, verbose_name='Last name')),
                ('role', models.CharField(blank=True, max_length=32, null=True, verbose_name='Role')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cred',
                'verbose_name_plural': 'Creds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=100, null=True, verbose_name='Operating System')),
                ('users', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Target',
                'verbose_name_plural': 'Targets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OplogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('src_ip', models.TextField(blank=True, null=True, verbose_name='Source IP')),
                ('src_port', models.TextField(blank=True, null=True, verbose_name='Source Port')),
                ('src_host', models.TextField(blank=True, null=True, verbose_name='Source Host')),
                ('dst_ip', models.TextField(blank=True, null=True, verbose_name='Destination IP')),
                ('dst_port', models.TextField(blank=True, null=True, verbose_name='Destination Port')),
                ('dst_host', models.TextField(blank=True, null=True, verbose_name='Destination Host')),
                ('url', models.TextField(blank=True, null=True, verbose_name='Target URL')),
                ('tool', models.TextField(blank=True, null=True, verbose_name='Tool Used')),
                ('command', models.TextField(blank=True, null=True, verbose_name='Command Executed')),
                ('output', models.TextField(blank=True, null=True, verbose_name='Command Output/Result')),
                ('notes', models.TextField(blank=True, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='oplog_screenshots/')),
                ('sys_mod', models.TextField(blank=True, null=True, verbose_name='System Modification')),
                ('exfil', models.FileField(blank=True, null=True, upload_to='oplog_exfil/')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oplog_entries', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oplog_entries', to='collector.target')),
            ],
            options={
                'verbose_name': 'Operator Log Entry',
                'verbose_name_plural': 'Operator Log Entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
