# Generated by Django 5.2.3 on 2026-10-05 15:19

import collector.models
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# collector.migrations.0017_populate_mitigations
# collector.migrations.0018_populate_mitigations
# collector.migrations.0027_populate_migrations
# collector.migrations.0030_populate_mitigations

class Migration(migrations.Migration):

    replaces = [('collector', '0001_initial'), ('collector', '0002_credential_delete_cred'), ('collector', '0003_alter_oplogentry_exfil'), ('collector', '0004_oplogentry_enum_enumerationdata'), ('collector', '0005_enumerationdata_oplog_source'), ('collector', '0006_payload'), ('collector', '0007_remove_oplogentry_dst_ip'), ('collector', '0008_remove_oplogentry_dst_host'), ('collector', '0009_exfilfile'), ('collector', '0010_remove_oplogentry_exfil'), ('collector', '0011_alter_oplogentry_src_ip'), ('collector', '0012_alter_oplogentry_notes'), ('collector', '0013_alter_oplogentry_dst_port_alter_oplogentry_src_port_and_more'), ('collector', '0014_alter_oplogentry_dst_port_alter_oplogentry_notes_and_more'), ('collector', '0015_alter_target_ip_address'), ('collector', '0016_mitigation_oplogentry_mitigations'), ('collector', '0017_populate_mitigations'), ('collector', '0018_populate_mitigations'), ('collector', '0019_alter_mitigation_finding_alter_mitigation_reference'), ('collector', '0020_alter_mitigation_reference'), ('collector', '0021_note'), ('collector', '0022_alter_note_options'), ('collector', '0023_populate_mitigations'), ('collector', '0024_alter_note_content'), ('collector', '0025_alter_oplogentry_target'), ('collector', '0026_alter_target_ip_address'), ('collector', '0027_populate_migrations'), ('collector', '0028_auto_20261005_1350'), ('collector', '0029_oplogscreenshot'), ('collector', '0030_populate_mitigations')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.TextField(blank=True, null=True, verbose_name='IP Address')),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=100, null=True, verbose_name='Operating System')),
                ('users', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Target',
                'verbose_name_plural': 'Targets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, help_text='e.g., SSH, SMB, RDP, HTTP Basic, Local Admin', max_length=100, null=True)),
                ('username', models.CharField(max_length=255)),
                ('password_plaintext', models.TextField(blank=True, null=True, verbose_name='Password/Secret (Plaintext - WARNING!)')),
                ('hash_value', models.TextField(blank=True, null=True, verbose_name='Hash Value')),
                ('hash_type', models.CharField(blank=True, help_text='e.g., NTLM, NetNTLMv1/v2, Kerberos, bcrypt', max_length=50, null=True, verbose_name='Hash Type')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_credentials', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to='collector.target')),
            ],
            options={
                'verbose_name': 'Credential',
                'verbose_name_plural': 'Credentials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OplogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('src_ip', models.TextField(blank=True, null=True, verbose_name='Source IP')),
                ('src_port', models.TextField(blank=True, max_length=14, null=True, verbose_name='Source Port')),
                ('src_host', models.TextField(blank=True, null=True, verbose_name='Source Host')),
                ('dst_port', models.TextField(blank=True, null=True, verbose_name='Destination Port')),
                ('url', models.TextField(blank=True, null=True, verbose_name='Target URL')),
                ('tool', models.TextField(blank=True, max_length=14, null=True, verbose_name='Tool Used')),
                ('command', models.TextField(blank=True, null=True, verbose_name='Command Executed')),
                ('output', models.TextField(blank=True, null=True, verbose_name='Command Output/Result')),
                ('notes', models.TextField(blank=True, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='oplog_screenshots/')),
                ('sys_mod', models.TextField(blank=True, null=True, verbose_name='System Modification')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oplog_entries', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oplog_entries', to='collector.target')),
                ('enum', models.FileField(blank=True, null=True, upload_to=collector.models.get_enum_data_path)),
            ],
            options={
                'verbose_name': 'Operator Log Entry',
                'verbose_name_plural': 'Operator Log Entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EnumerationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(blank=True, help_text='e.g., Nmap, Nessus, Dirb, Manual Notes, Recon-ng', max_length=100, null=True)),
                ('description', models.CharField(blank=True, help_text='Brief description of the scan/data', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('scan_file', models.FileField(blank=True, null=True, upload_to=collector.models.get_enum_data_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_enum_data', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enum_data', to='collector.target')),
                ('oplog_source', models.OneToOneField(blank=True, help_text='The Oplog entry this data was created from (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_enum_data', to='collector.oplogentry')),
            ],
            options={
                'verbose_name': 'Enumeration Data',
                'verbose_name_plural': 'Enumeration Data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Filename or a descriptive name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Purpose, usage, C2 info, etc.', null=True)),
                ('payload_type', models.CharField(choices=[('EXE', 'Executable (exe, dll, etc.)'), ('SCRIPT', 'Script (ps1, py, js, sh, etc.)'), ('SHELLCODE', 'Shellcode'), ('CONFIG', 'Configuration (xml, json, yaml)'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('file', models.FileField(upload_to=collector.models.get_payload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_payloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payload',
                'verbose_name_plural': 'Payloads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExfilFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=collector.models.get_oplog_exfil_path)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('oplog_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exfil_files', to='collector.oplogentry')),
            ],
            options={
                'verbose_name': 'Exfiltrated File',
                'verbose_name_plural': 'Exfiltrated Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Mitigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short unique name/ID (e.g., M1, Disable Outdated Service SMBv1)', max_length=100, unique=True)),
                ('finding', models.CharField(blank=True, help_text='Short unique name/ID (e.g., Insecure Protocol or Service)', max_length=100)),
                ('description', models.TextField(help_text='Detailed description of the mitigation.')),
                ('category', models.CharField(blank=True, help_text='Optional category (e.g., Network, Host, Policy, IAM)', max_length=50)),
                ('reference', models.TextField(blank=True, help_text='Optional reference.', max_length=500)),
            ],
            options={
                'verbose_name': 'Mitigation',
                'verbose_name_plural': 'Mitigations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='oplogentry',
            name='mitigations',
            field=models.ManyToManyField(blank=True, related_name='oplog_entries', to='collector.mitigation', verbose_name='Associated Mitigations'),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='finding',
            field=models.CharField(blank=True, help_text='Short unique name/ID (e.g., Insecure Protocols or Services)', max_length=100),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='reference',
            field=models.TextField(blank=True, help_text='Optional URL to external documentation.', max_length=500),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='short title', max_length=255)),
                ('content', models.TextField(blank=True, help_text='Main content.')),
                ('category', models.CharField(blank=True, help_text='Optional category (e.g., Scope, POC, Rules, Findings, TODO).', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrative Note',
                'verbose_name_plural': 'Administrative Notes',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='oplogentry',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oplog_entries', to='collector.target'),
        ),
        migrations.AlterField(
            model_name='target',
            name='ip_address',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='IP Address'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OplogScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=collector.models.oplog_screenshot_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('oplog_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='collector.oplogentry')),
            ],
        ),
    ]
