# Generated by Django 5.2 on 2025-04-15 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, help_text='e.g., SSH, SMB, RDP, HTTP Basic, Local Admin', max_length=100, null=True)),
                ('username', models.CharField(max_length=255)),
                ('password_plaintext', models.TextField(blank=True, null=True, verbose_name='Password/Secret (Plaintext - WARNING!)')),
                ('hash_value', models.TextField(blank=True, null=True, verbose_name='Hash Value')),
                ('hash_type', models.CharField(blank=True, help_text='e.g., NTLM, NetNTLMv1/v2, Kerberos, bcrypt', max_length=50, null=True, verbose_name='Hash Type')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_credentials', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to='collector.target')),
            ],
            options={
                'verbose_name': 'Credential',
                'verbose_name_plural': 'Credentials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Cred',
        ),
    ]
