# Generated by Django 5.2 on 2025-04-16 13:33

import collector.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_credential_delete_cred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oplogentry',
            name='exfil',
            field=models.FileField(blank=True, null=True, upload_to=collector.models.get_oplog_exfil_path),
        ),
    ]
