# Generated by Django 5.2 on 2025-04-16 13:52

import collector.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_alter_oplogentry_exfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oplogentry',
            name='enum',
            field=models.FileField(blank=True, null=True, upload_to=collector.models.get_enum_data_path),
        ),
        migrations.CreateModel(
            name='EnumerationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(blank=True, help_text='e.g., Nmap, Nessus, Dirb, Manual Notes, Recon-ng', max_length=100, null=True)),
                ('description', models.CharField(blank=True, help_text='Brief description of the scan/data', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('scan_file', models.FileField(blank=True, null=True, upload_to=collector.models.get_enum_data_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_enum_data', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enum_data', to='collector.target')),
            ],
            options={
                'verbose_name': 'Enumeration Data',
                'verbose_name_plural': 'Enumeration Data',
                'ordering': ['-created_at'],
            },
        ),
    ]
