# Generated by Django 5.2 on 2025-04-16 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_oplogentry_enum_enumerationdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='enumerationdata',
            name='oplog_source',
            field=models.OneToOneField(blank=True, help_text='The Oplog entry this data was created from (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_enum_data', to='collector.oplogentry'),
        ),
    ]
