# Generated by Django 5.2 on 2025-04-16 18:37

import collector.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_enumerationdata_oplog_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Filename or a descriptive name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Purpose, usage, C2 info, etc.', null=True)),
                ('payload_type', models.CharField(choices=[('EXE', 'Executable (exe, dll, etc.)'), ('SCRIPT', 'Script (ps1, py, js, sh, etc.)'), ('SHELLCODE', 'Shellcode'), ('CONFIG', 'Configuration (xml, json, yaml)'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('file', models.FileField(upload_to=collector.models.get_payload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_payloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payload',
                'verbose_name_plural': 'Payloads',
                'ordering': ['-created_at'],
            },
        ),
    ]
