# Generated by Django 5.2 on 2025-04-17 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0006_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oplogentry',
            name='dst_ip',
        ),
    ]
