# Generated by Django 5.2 on 2025-04-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_remove_oplogentry_dst_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oplogentry',
            name='dst_host',
        ),
    ]
