# Generated by Django 5.2 on 2025-04-17 12:46

import collector.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_remove_oplogentry_dst_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExfilFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=collector.models.get_oplog_exfil_path)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('oplog_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exfil_files', to='collector.oplogentry')),
            ],
            options={
                'verbose_name': 'Exfiltrated File',
                'verbose_name_plural': 'Exfiltrated Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
