# Generated by Django 5.2 on 2025-04-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0010_remove_oplogentry_exfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oplogentry',
            name='src_ip',
            field=models.TextField(blank=True, max_length=14, null=True, verbose_name='Source IP'),
        ),
    ]
