# Generated by Django 5.2 on 2025-04-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0011_alter_oplogentry_src_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oplogentry',
            name='notes',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
