# Generated by Django 5.2 on 2025-04-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0012_alter_oplogentry_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oplogentry',
            name='dst_port',
            field=models.TextField(blank=True, max_length=14, null=True, verbose_name='Destination Port'),
        ),
        migrations.AlterField(
            model_name='oplogentry',
            name='src_port',
            field=models.TextField(blank=True, max_length=14, null=True, verbose_name='Source Port'),
        ),
        migrations.AlterField(
            model_name='oplogentry',
            name='tool',
            field=models.TextField(blank=True, max_length=14, null=True, verbose_name='Tool Used'),
        ),
    ]
