# Generated by Django 5.2 on 2025-04-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0013_alter_oplogentry_dst_port_alter_oplogentry_src_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oplogentry',
            name='dst_port',
            field=models.TextField(blank=True, null=True, verbose_name='Destination Port'),
        ),
        migrations.AlterField(
            model_name='oplogentry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oplogentry',
            name='src_ip',
            field=models.TextField(blank=True, null=True, verbose_name='Source IP'),
        ),
    ]
