# Generated by Django 5.2 on 2025-04-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0014_alter_oplogentry_dst_port_alter_oplogentry_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='ip_address',
            field=models.TextField(blank=True, null=True, verbose_name='IP Address'),
        ),
    ]
