# Generated by Django 5.2 on 2025-04-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0015_alter_target_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mitigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short unique name/ID (e.g., M1, Disable Outdated Service SMBv1)', max_length=100, unique=True)),
                ('finding', models.CharField(help_text='Short unique name/ID (e.g., Insecure Protocol or Service)', max_length=100, blank=True)),
                ('description', models.TextField(help_text='Detailed description of the mitigation.')),
                ('category', models.CharField(blank=True, help_text='Optional category (e.g., Network, Host, Policy, IAM)', max_length=50)),
                ('reference', models.TextField(blank=True, help_text='Optional reference.', max_length=500)),
            ],
            options={
                'verbose_name': 'Mitigation',
                'verbose_name_plural': 'Mitigations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='oplogentry',
            name='mitigations',
            field=models.ManyToManyField(blank=True, related_name='oplog_entries', to='collector.mitigation', verbose_name='Associated Mitigations'),
        ),
    ]
