# Generated by Django 5.2 on 2025-04-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0018_populate_mitigations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitigation',
            name='finding',
            field=models.CharField(blank=True, help_text='Short unique name/ID (e.g., Insecure Protocols or Services)', max_length=100),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='reference',
            field=models.URLField(blank=True, help_text='Optional URL to external documentation.', max_length=500),
        ),
    ]
