# Generated by Django 5.2 on 2025-04-25 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0020_alter_mitigation_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='short title', max_length=255)),
                ('content', models.TextField(blank=True, help_text='Main content, markdown can be used if configured.')),
                ('category', models.CharField(blank=True, help_text='Optional category (e.g., Scope, POC, Rules, Findings, TODO).', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'General Note',
                'verbose_name_plural': 'General Notes',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
