# Generated by Django 5.2 on 2025-04-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0021_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'Administrative Note', 'verbose_name_plural': 'Administrative Notes'},
        ),
    ]
