# Generated by Django 5.2 on 2025-04-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0022_alter_note_options'),
    ]

    operations = [
    ]
