# Generated by Django 5.2 on 2025-04-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0023_populate_mitigations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, help_text='Main content.'),
        ),
    ]
