# Generated by Django 5.2.3 on 2025-06-27 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0024_alter_note_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oplogentry',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oplog_entries', to='collector.target'),
        ),
    ]
