# Generated by Django 5.2.3 on 2025-07-08 16:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0025_alter_oplogentry_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='ip_address',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='IP Address'),
            preserve_default=False,
        ),
    ]
