# Generated by Django 5.2.3 on 2026-10-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0027_populate_migrations'),
    ]

    operations = [
    ]
