# Generated by Django 5.2.3 on 2026-10-05 14:14

import collector.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0028_auto_20261005_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='OplogScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=collector.models.oplog_screenshot_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('oplog_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='collector.oplogentry')),
            ],
        ),
    ]
