# Generated by Django 2.2.6 on 2019-10-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oplog',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='oplog',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
