# Generated by Django 2.2.6 on 2019-11-05 16:58

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc', '0007_auto_20191031_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='payloadinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inf', models.CharField(blank=True, max_length=100)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('ip', models.CharField(blank=True, max_length=60)),
                ('proto', models.CharField(blank=True, max_length=100)),
                ('usage', models.CharField(blank=True, max_length=300)),
                ('payld', models.CharField(blank=True, max_length=1000)),
                ('payldfile', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/protected', location='/var/www/edc_app/protected'), upload_to='')),
            ],
        ),
    ]
